server:
  port: 9001
spring:
  application:
    name: PINXIXI-PRODUCT
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///pinxixi?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
mybatis-plus:
  type-aliases-package: cn.itsource.pinxixi.domain,cn.itsource.pinxixi.query